export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE';

export const LOADED_ITEM_IN_WISHLIST = 'LOADED_ITEM_IN_WISHLIST';
export const ADDED_ITEM_IN_WISHLIST = 'ADDED_ITEM_IN_WISHLIST';
export const REMOVED_ITEM_FROM_WISHLIST = 'REMOVED_ITEM_FROM_WISHLIST';

export const LOADED_ITEM_IN_CART = 'LOADED_ITEM_IN_CART';
export const ADDED_ITEM_IN_CART = 'ADDED_ITEM_IN_CART';
export const REMOVED_ITEM_FROM_CART = 'REMOVED_ITEM_FROM_CART';

export const LOADED_ITEM_IN_CART_GUI = 'LOADED_ITEM_IN_CART_GUI';
export const ADDED_ITEM_IN_CART_GUI = 'ADDED_ITEM_IN_CART_GUI';
export const REMOVED_ITEM_FROM_CART_GUI = 'REMOVED_ITEM_FROM_CART_GUI';

export const LOADED_ITEM_IN_WISHLIST_GUI = 'LOADED_ITEM_IN_WISHLIST_GUI';
export const ADDED_ITEM_IN_WISHLIST_GUI = 'ADDED_ITEM_IN_WISHLIST_GUI';
export const REMOVED_ITEM_FROM_WISHLIST_GUI = 'REMOVED_ITEM_FROM_WISHLIST_GUI';

export const ON_COST_CHANGED = 'ON_COST_CHANGED';
export const ON_QONT_UPDATE = 'ON_QONT_UPDATE';

export const ON_PROFILE_LOAD = 'ON_PROFILE_LOAD';

export const ON_ORDERS_LOAD = 'ON_ORDERS_LOAD';

export const CLEAR_DATA = 'CLEAR_DATA';